# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pyqt_ros2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(665, 356)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 50, 611, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_ros2_state_float = QtWidgets.QLabel(self.tab)
        self.label_ros2_state_float.setEnabled(True)
        self.label_ros2_state_float.setMaximumSize(QtCore.QSize(130, 30))
        self.label_ros2_state_float.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ros2_state_float.setFont(font)
        self.label_ros2_state_float.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_ros2_state_float.setText("")
        self.label_ros2_state_float.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ros2_state_float.setIndent(3)
        self.label_ros2_state_float.setObjectName("label_ros2_state_float")
        self.gridLayout.addWidget(self.label_ros2_state_float, 0, 2, 2, 1, QtCore.Qt.AlignVCenter)
        self.checkBox_float_02 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_float_02.setText("")
        self.checkBox_float_02.setObjectName("checkBox_float_02")
        self.gridLayout.addWidget(self.checkBox_float_02, 2, 0, 1, 1)
        self.label_msg_float = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_msg_float.setFont(font)
        self.label_msg_float.setObjectName("label_msg_float")
        self.gridLayout.addWidget(self.label_msg_float, 2, 1, 1, 1)
        self.label_topic_changed_float = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_topic_changed_float.setFont(font)
        self.label_topic_changed_float.setObjectName("label_topic_changed_float")
        self.gridLayout.addWidget(self.label_topic_changed_float, 5, 1, 1, 1)
        self.label_data_num_float = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_data_num_float.setFont(font)
        self.label_data_num_float.setText("")
        self.label_data_num_float.setIndent(3)
        self.label_data_num_float.setObjectName("label_data_num_float")
        self.gridLayout.addWidget(self.label_data_num_float, 2, 2, 1, 1)
        self.lineEdit_topic_float = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_topic_float.setFont(font)
        self.lineEdit_topic_float.setObjectName("lineEdit_topic_float")
        self.gridLayout.addWidget(self.lineEdit_topic_float, 5, 2, 1, 1)
        self.checkBox_float_01 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_float_01.setText("")
        self.checkBox_float_01.setObjectName("checkBox_float_01")
        self.gridLayout.addWidget(self.checkBox_float_01, 0, 0, 2, 1)
        self.label_ros2_float = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(13)
        self.label_ros2_float.setFont(font)
        self.label_ros2_float.setObjectName("label_ros2_float")
        self.gridLayout.addWidget(self.label_ros2_float, 0, 1, 2, 1)
        self.label_topic_name_float = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_topic_name_float.setFont(font)
        self.label_topic_name_float.setObjectName("label_topic_name_float")
        self.gridLayout.addWidget(self.label_topic_name_float, 3, 1, 2, 1)
        self.label_topic_setting_float = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_topic_setting_float.setFont(font)
        self.label_topic_setting_float.setText("")
        self.label_topic_setting_float.setIndent(3)
        self.label_topic_setting_float.setObjectName("label_topic_setting_float")
        self.gridLayout.addWidget(self.label_topic_setting_float, 3, 2, 2, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_topic_int = QtWidgets.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_topic_int.setFont(font)
        self.lineEdit_topic_int.setObjectName("lineEdit_topic_int")
        self.gridLayout_2.addWidget(self.lineEdit_topic_int, 5, 2, 1, 1)
        self.label_topic_name_int = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_topic_name_int.setFont(font)
        self.label_topic_name_int.setObjectName("label_topic_name_int")
        self.gridLayout_2.addWidget(self.label_topic_name_int, 3, 1, 2, 1)
        self.label_data_num_int = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_data_num_int.setFont(font)
        self.label_data_num_int.setText("")
        self.label_data_num_int.setObjectName("label_data_num_int")
        self.gridLayout_2.addWidget(self.label_data_num_int, 2, 2, 1, 1)
        self.checkBox_int_01 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_int_01.setText("")
        self.checkBox_int_01.setObjectName("checkBox_int_01")
        self.gridLayout_2.addWidget(self.checkBox_int_01, 0, 0, 2, 1)
        self.label_topic_setting_int = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_topic_setting_int.setFont(font)
        self.label_topic_setting_int.setText("")
        self.label_topic_setting_int.setObjectName("label_topic_setting_int")
        self.gridLayout_2.addWidget(self.label_topic_setting_int, 3, 2, 2, 1)
        self.checkBox_int_02 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_int_02.setText("")
        self.checkBox_int_02.setObjectName("checkBox_int_02")
        self.gridLayout_2.addWidget(self.checkBox_int_02, 2, 0, 1, 1)
        self.label_msg_int = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_msg_int.setFont(font)
        self.label_msg_int.setObjectName("label_msg_int")
        self.gridLayout_2.addWidget(self.label_msg_int, 2, 1, 1, 1)
        self.label_topic_changed_int = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_topic_changed_int.setFont(font)
        self.label_topic_changed_int.setObjectName("label_topic_changed_int")
        self.gridLayout_2.addWidget(self.label_topic_changed_int, 5, 1, 1, 1)
        self.label_ros2_int = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(13)
        self.label_ros2_int.setFont(font)
        self.label_ros2_int.setObjectName("label_ros2_int")
        self.gridLayout_2.addWidget(self.label_ros2_int, 0, 1, 2, 1)
        self.label_ros2_state_int = QtWidgets.QLabel(self.tab_2)
        self.label_ros2_state_int.setEnabled(True)
        self.label_ros2_state_int.setMaximumSize(QtCore.QSize(130, 30))
        self.label_ros2_state_int.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ros2_state_int.setFont(font)
        self.label_ros2_state_int.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_ros2_state_int.setText("")
        self.label_ros2_state_int.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ros2_state_int.setIndent(3)
        self.label_ros2_state_int.setObjectName("label_ros2_state_int")
        self.gridLayout_2.addWidget(self.label_ros2_state_int, 0, 2, 2, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.label_main = QtWidgets.QLabel(self.centralwidget)
        self.label_main.setGeometry(QtCore.QRect(20, 20, 621, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setItalic(False)
        self.label_main.setFont(font)
        self.label_main.setObjectName("label_main")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 665, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyQt5 ROS2 APP"))
        self.label_msg_float.setText(_translate("MainWindow", "Float64 msg"))
        self.label_topic_changed_float.setText(_translate("MainWindow", "Topic Changed:"))
        self.label_ros2_float.setText(_translate("MainWindow", "ROS2 Connection"))
        self.label_topic_name_float.setText(_translate("MainWindow", "Topic Name:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Float_msg"))
        self.label_topic_name_int.setText(_translate("MainWindow", "Topic Name:"))
        self.label_msg_int.setText(_translate("MainWindow", "Int64 msg"))
        self.label_topic_changed_int.setText(_translate("MainWindow", "Topic Changed:"))
        self.label_ros2_int.setText(_translate("MainWindow", "ROS2 Connection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Int_msg"))
        self.label_main.setText(_translate("MainWindow", "Subscribe ROS2 Data"))
